basePath: /v1
definitions:
  authors.Author:
    properties:
      bio:
        example: 998th Lord Commander of the Night's Watch
        type: string
      id:
        example: 28487cdf-6694-4efb-9916-c0d5f596ed06
        type: string
      name:
        example: Jon Snow
        type: string
    type: object
  authors.CreateAuthorDto:
    properties:
      bio:
        example: 998th Lord Commander of the Night's Watch
        type: string
      name:
        example: Jon Snow
        minLength: 2
        type: string
    required:
    - name
    type: object
  authors.UpdateAuthorDto:
    properties:
      bio:
        example: King Aegon of Houses Targaryen and Stark
        type: string
      name:
        example: Aegon Targaryen
        minLength: 2
        type: string
    type: object
  titles.CreateTitleDto:
    properties:
      id_author:
        example: 28487cdf-6694-4efb-9916-c0d5f596ed06
        type: string
      name:
        example: Lord of Mysteries
        minLength: 2
        type: string
    required:
    - name
    type: object
  titles.Title:
    properties:
      id:
        example: 28487cdf-6694-4efb-9916-c0d5f596ed06
        type: string
      id_author:
        example: 28487cdf-6694-4efb-9916-c0d5f596ed06
        type: string
      name:
        example: Lord of Mysteries
        type: string
    type: object
  titles.UpdateTitleDto:
    properties:
      id_author:
        example: 28487cdf-6694-4efb-9916-c0d5f596ed06
        type: string
      name:
        example: Circle of Inevitably
        minLength: 2
        type: string
    type: object
  util.ApiError:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: SS API
  version: "1.0"
paths:
  /authors/:
    get:
      consumes:
      - application/json
      description: Get a list of all authors
      operationId: getAll
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/authors.Author'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ApiError'
      summary: List all authors
      tags:
      - authors
    post:
      consumes:
      - application/json
      description: Create a new author
      operationId: create
      parameters:
      - description: Author data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/authors.CreateAuthorDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/authors.Author'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ApiError'
      summary: Create author
      tags:
      - authors
  /authors/{id}:
    delete:
      consumes:
      - application/json
      description: Delete an existing author by ID
      operationId: deleteById
      parameters:
      - description: Author ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ApiError'
      summary: Delete author
      tags:
      - authors
    get:
      consumes:
      - application/json
      description: Retrieve a single author by their ID
      operationId: getById
      parameters:
      - description: Author ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/authors.Author'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/util.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ApiError'
      summary: Get author by ID
      tags:
      - authors
    put:
      consumes:
      - application/json
      description: Update an existing author by ID
      operationId: updateById
      parameters:
      - description: Author ID
        in: path
        name: id
        required: true
        type: string
      - description: Author data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/authors.UpdateAuthorDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/authors.Author'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ApiError'
      summary: Update author
      tags:
      - authors
  /titles/:
    get:
      consumes:
      - application/json
      description: Get a list of all titles
      operationId: getAll
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/titles.Title'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ApiError'
      summary: List all titles
      tags:
      - titles
    post:
      consumes:
      - application/json
      description: Create a new title
      operationId: create
      parameters:
      - description: Title data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/titles.CreateTitleDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/titles.Title'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ApiError'
      summary: Create title
      tags:
      - titles
  /titles/{id}:
    delete:
      consumes:
      - application/json
      description: Delete an existing title by ID
      operationId: deleteById
      parameters:
      - description: Title ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ApiError'
      summary: Delete title
      tags:
      - titles
    get:
      consumes:
      - application/json
      description: Retrieve a single title by their ID
      operationId: getById
      parameters:
      - description: Title ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/titles.Title'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/util.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ApiError'
      summary: Get title by ID
      tags:
      - titles
    put:
      consumes:
      - application/json
      description: Update an existing title by ID
      operationId: updateById
      parameters:
      - description: Title ID
        in: path
        name: id
        required: true
        type: string
      - description: Title data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/titles.UpdateTitleDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/titles.Title'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ApiError'
      summary: Update title
      tags:
      - titles
swagger: "2.0"
