services:
  app:
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
    command: ./api
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    configs:
      - source: init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

configs:
  init.sql:
    content: |
      CREATE DATABASE test;

      \c test;

      CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

      CREATE TABLE authors (
        id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        name VARCHAR(255) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP      
      )