name: Publish openapi spec on gh-pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'

      - run: |
          go get github.com/swaggo/swag/cmd/swag@v1.16.6
          go run github.com/swaggo/swag/cmd/swag@v1.16.6 init -g ./cmd/main.go

      - run: |
          cat <<EOF >> docs/index.html
            <!doctype html>
            <html>
              <head>
                <title>SS Api</title>
                <meta charset="utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
              </head>

              <body>
                <div id="app"></div>
                <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
                <script>
                  Scalar.createApiReference('#app', { url: 'https://souzaramon.github.io/ss-api/swagger.json', theme: 'solarized' })
                </script>
              </body>
            </html>
          EOF

      - uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs

      - run: |
          PACKAGE_NAME="ss-api-http-client"
          TEMP_DIR=$(mktemp -d)

          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/souzaramon/$PACKAGE_NAME.git "$TEMP_DIR"
          npm install -g @openapitools/openapi-generator-cli
          openapi-generator-cli generate -i docs/swagger.json -g typescript-axios -o "$TEMP_DIR"

          chmod +x "$TEMP_DIR/git_push.sh"

          LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
          cd "$TEMP_DIR"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          ./git_push.sh "${{ github.actor }}" "$PACKAGE_NAME" "$LAST_COMMIT_MSG" "github.com"
        env:
          GIT_TOKEN: ${{ secrets.GH_TOKEN }}
